name: CMake

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: volumectl
        path: ${{github.workspace}}\build\${{env.BUILD_TYPE}}\*.exe
        if-no-files-found: error
